# Site settings
title: Tommy Lee
email: tommy@tommylee.co
github: http://github.com/tomcentrate
description: Developing with a human-oriented architecture
url: "http://tommylee.co" # the base hostname & protocol for your site
locale: en-US
timezone: America/New_York

highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown
paginate: 5

# About/contact
author:
  name:              Tommy Lee
  url:               https://twitter.com/mdo
  email:             tommy@tommylee.co

# Custom vars
version:             1.0.0
