# Site wide configuration

title: 'Tomcentrate'
description: 'Programming and Fried Chicken'
logo: apple-touch-icon-120x120.png # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en-US
url: 

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Tommy Lee
  email: tommy.t.lee@gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: Web developer with an unhealthy dose of skepticism.
  avatar: bio-photo.png # 160x160 px image for author byline
disqus-shortname: 


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
