# Site wide configuration

title: 'Tomcentrate'
description: 'High anxiety programming'
logo: apple-touch-icon-120x120.png # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en-US
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    # style: compressed
permalink: articles/:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from


# Site owner
owner:
  name: Tommy Lee
  email: tommy.t.lee@gmail.com
  twitter: tomcentrate
  google:
    ad-client:
    ad-slot:
  bio: Putting the 'human' back in 'humanoid business solutions automaton'
  avatar: bio-photo.png # 160x160 px image for author byline
disqus-shortname: tomcentrate


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
