# Site settings
title: Tommy Lee
email: tommy@tommylee.co
github: http://github.com/tomcentrate
github_edit_post_repo: https://github.com/tomcentrate/tomcentrate.github.io/
linkedin: https://www.linkedin.com/in/tommy-lee-a23ba935
resume: https://tommylee.co/resume/
description: Software development for everyone else
tagline: Software development for everyone else
url: "http://tommylee.co" # the base hostname & protocol for your site
locale: en-US
timezone: America/New_York


permalink: none

highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
# Build settings
markdown: kramdown
paginate: 5

# About/contact
author:
  name:              Tommy Lee
  url:               https://twitter.com/tomcentrate
  email:             tommy@tommylee.co

# Custom vars
version:             1.0.0
